/* ==========================================================================
 * Copyright 2003-2004 Mevenide Team
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 * =========================================================================
 */
package org.mevenide.netbeans.project.customizer;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Iterator;

import java.util.List;
import java.util.Map;
import java.util.HashMap;
import javax.swing.JButton;

import javax.swing.JPanel;
import javax.swing.JTextField;
import org.mevenide.netbeans.api.customizer.ProjectPanel;
import org.mevenide.netbeans.api.customizer.ProjectValidateObserver;
import org.mevenide.netbeans.api.customizer.changes.MavenChange;
import org.mevenide.netbeans.api.customizer.changes.MultiTextComponentPOMChange;
import org.mevenide.netbeans.api.customizer.changes.TextComponentPOMChange;
import org.mevenide.netbeans.api.project.MavenProject;
import org.mevenide.netbeans.api.customizer.LocationComboFactory;
import org.mevenide.netbeans.api.customizer.OriginChange;
import org.mevenide.project.io.IContentProvider;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.awt.HtmlBrowser;
import org.apache.maven.project.Repository;

/**
 *
 * @author  Milos Kleint (ca206216@tiscali.cz)
 */
public class RepositoryPanel extends JPanel implements ProjectPanel {
    
    private ProjectValidateObserver valObserver;
    private MavenProject project;
    
    private OriginChange ocGumpID;
    private OriginChange ocRepository;
    
    private HashMap changes;
    private boolean initialized;
    
    /** Creates new form BasicsPanel */
    public RepositoryPanel(MavenProject proj) {
        project = proj;
        changes = new HashMap();
        initComponents();
        valObserver = null;
        //TODO add listeners for immediatePropagation stuff.
        setName("Repository");
        btnURL.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent event) {
                String url = txtURL.getText().trim();
                url = project.getPropertyResolver().resolveString(url);
                if (url.startsWith("http://")) { //NOI18N
                    try {
                        URL link = new URL(url);
                        HtmlBrowser.URLDisplayer.getDefault().showURL(link);
                    } catch (MalformedURLException exc) {
                        NotifyDescriptor error = new NotifyDescriptor.Message("Is not a valid URL.", NotifyDescriptor.WARNING_MESSAGE);
                        DialogDisplayer.getDefault().notify(error);
                    }
                }
            }
        });
        initialized = false;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        ocRepository = LocationComboFactory.createPOMChange(project, true);
        btnRepository = (JButton)ocRepository.getComponent();
        pnlRepo = new javax.swing.JPanel();
        lblConnection = new javax.swing.JLabel();
        txtConnection = new javax.swing.JTextField();
        lblURL = new javax.swing.JLabel();
        txtURL = new javax.swing.JTextField();
        lblDevConnection = new javax.swing.JLabel();
        txtDevConnection = new javax.swing.JTextField();
        btnURL = new javax.swing.JButton();
        lblGumpRepoID = new javax.swing.JLabel();
        txtGumpRepoID = new javax.swing.JTextField();
        ocGumpID = LocationComboFactory.createPOMChange(project, false);
        btnGumpID = (JButton)ocGumpID.getComponent();

        jPanel1 = new javax.swing.JPanel();
        lblRepository = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 6, 0);
        add(btnRepository, gridBagConstraints);

        pnlRepo.setLayout(new java.awt.GridBagLayout());

        pnlRepo.setBorder(new javax.swing.border.EtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        lblConnection.setLabelFor(txtConnection);
        lblConnection.setText("Connection:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        pnlRepo.add(lblConnection, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 0, 0);
        pnlRepo.add(txtConnection, gridBagConstraints);

        lblURL.setLabelFor(txtURL);
        lblURL.setText("URL :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 0);
        pnlRepo.add(lblURL, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 0);
        pnlRepo.add(txtURL, gridBagConstraints);

        lblDevConnection.setLabelFor(txtDevConnection);
        lblDevConnection.setText("Developer Conn:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        pnlRepo.add(lblDevConnection, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 0, 0);
        pnlRepo.add(txtDevConnection, gridBagConstraints);

        btnURL.setText("View...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 6, 6);
        pnlRepo.add(btnURL, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(pnlRepo, gridBagConstraints);

        lblGumpRepoID.setLabelFor(txtGumpRepoID);
        lblGumpRepoID.setText("Gump Repository ID:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        add(lblGumpRepoID, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 0, 0);
        add(txtGumpRepoID, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(btnGumpID, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 0.1;
        add(jPanel1, gridBagConstraints);

        lblRepository.setText("Repository:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        add(lblRepository, gridBagConstraints);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGumpID;
    private javax.swing.JButton btnRepository;
    private javax.swing.JButton btnURL;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblConnection;
    private javax.swing.JLabel lblDevConnection;
    private javax.swing.JLabel lblGumpRepoID;
    private javax.swing.JLabel lblRepository;
    private javax.swing.JLabel lblURL;
    private javax.swing.JPanel pnlRepo;
    private javax.swing.JTextField txtConnection;
    private javax.swing.JTextField txtDevConnection;
    private javax.swing.JTextField txtGumpRepoID;
    private javax.swing.JTextField txtURL;
    // End of variables declaration//GEN-END:variables
   
   public void addNotify() {
        super.addNotify();
        if (!initialized) {
            initialized = true;
            populateChangeInstances();
        }
   }
   
  private void populateChangeInstances() {
        createChangeInstance("gumpRepositoryId", txtGumpRepoID, ocGumpID); //NOI18N
        Repository repo = project.getOriginalMavenProject().getRepository();
        String key = "pom.repository"; //NOI18N
        int location = project.getProjectWalker().getLocation(key);
        Map oldValues = new HashMap();
        if (repo != null) {
            if (repo.getUrl() != null) {
                oldValues.put("url", repo.getUrl()); //NOI18N
            }
            if (repo.getConnection() != null) {
                oldValues.put("connection", repo.getConnection()); //NOI18N
            }
            if (repo.getDeveloperConnection() != null) {
                oldValues.put("developerConnection", repo.getDeveloperConnection()); //NOI18N
            }
        }
        HashMap fields = new HashMap();
        fields.put("url", txtURL); //NOI18N
        fields.put("connection", txtConnection); //NOI18N
        fields.put("developerConnection", txtDevConnection); //NOI18N
        changes.put(key, new MultiTextComponentPOMChange(key, oldValues, location, fields, ocRepository));
   }
   
   private void createChangeInstance(String propName, JTextField field, OriginChange oc) {
       String key = "pom." + propName; //NOI18N
       String value = project.getProjectWalker().getValue(key);
       int location = project.getProjectWalker().getLocation(key);
       if (value == null) {
           value = "";
       } 
       changes.put(key, new TextComponentPOMChange(key, value, location, field, oc));
   }    
   
   public void setResolveValues(boolean resolve) {
       assignValue("gumpRepositoryId", resolve); //NOI18N
       MultiTextComponentPOMChange change = (MultiTextComponentPOMChange)changes.get("pom.repository"); //NOI18N
       if (resolve) {
           IContentProvider prov = change.getChangedContent();
           HashMap resolvedvalues = new HashMap();
           String val = prov.getValue("url"); //NOI18N
           if (val != null) {
               resolvedvalues.put("url", project.getPropertyResolver().resolveString(val)); //NOI18N
           }
           val = prov.getValue("connection"); //NOI18N
           if (val != null) {
               resolvedvalues.put("connection", project.getPropertyResolver().resolveString(val)); //NOI18N
           }           
           val = prov.getValue("developerConnection"); //NOI18N
           if (val != null) {
               resolvedvalues.put("developerConnection", project.getPropertyResolver().resolveString(val)); //NOI18N
           }           
           change.setResolvedValues(resolvedvalues);
       } else {
           change.resetToNonResolvedValue();
       }
   }
    
   private void assignValue(String actionName, boolean resolve) {
       String key = "pom." + actionName; //NOI18N
       TextComponentPOMChange change = (TextComponentPOMChange)changes.get(key);
       if (resolve) {
           String value = project.getPropertyResolver().resolveString(change.getNewValue());
           change.setResolvedValue(value);
       } else {
           change.resetToNonResolvedValue();
       }
   }
     
    
//    private String getValue(String value, boolean resolve) {
//        if (resolve) {
//            return project.getPropertyResolver().resolveString(value);
//        }
//        return value;
//    }
    
    public List getChanges() {
        List toReturn = new ArrayList();
        Iterator it = changes.values().iterator();
        while (it.hasNext()) {
            MavenChange change = (MavenChange)it.next();
            if (change.hasChanged()) {
                toReturn.add(change);
            }
        }
        return toReturn;
    }
    
    public boolean isInValidState() {
        //TODO some checks..
        return true;
    }
    
    public void setValidateObserver(ProjectValidateObserver observer) {
        valObserver = observer;
    }
    
    public String getValidityMessage() {
        return "";
    }
    
}
