/* ==========================================================================
 * Copyright 2003-2004 Apache Software Foundation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 * =========================================================================
 */
package org.mevenide.netbeans.project.customizer;

import java.awt.BorderLayout;
import java.awt.GridBagConstraints;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.beans.PropertyVetoException;
import java.util.Collections;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.tree.TreeSelectionModel;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.maven.project.Dependency;
import org.apache.maven.project.Project;
import org.mevenide.netbeans.project.MavenProject;
import org.mevenide.netbeans.project.dependencies.DependencyNode;
import org.mevenide.netbeans.project.dependencies.DependencyPanel;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.view.BeanTreeView;
import org.openide.nodes.AbstractNode;
import org.openide.nodes.Children;
import org.openide.nodes.Node;


/**
 *
 * @author  Milos Kleint (ca206216@tiscali.cz)
 */
public class DependencyCustomizer extends JPanel implements ExplorerManager.Provider {
    private static final Log logger = LogFactory.getLog(DependencyCustomizer.class);
    
    private MavenProject project;
    private ExplorerManager manager;
    private DependencyPanel currentCustomizer;
    private BeanTreeView btv;
    
    /** Creates new form CustomGoalsPanel */
    public DependencyCustomizer(MavenProject project) {
        this.project = project;
        initComponents();
        GridBagConstraints fillConstraints = new GridBagConstraints();
        fillConstraints.gridwidth = GridBagConstraints.REMAINDER;
        fillConstraints.gridheight = GridBagConstraints.REMAINDER;
        fillConstraints.fill = GridBagConstraints.BOTH;
        fillConstraints.weightx = 1.0;
        fillConstraints.weighty = 1.0;
        
        manager = new ExplorerManager();
        btv = new BeanTreeView();    // Add the BeanTreeView
        btv.setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION );
        btv.setPopupAllowed( false );
        btv.setRootVisible( false );
        btv.setDefaultActionAllowed( false );
        pnlDeps.add(btv, fillConstraints);
        manager.addPropertyChangeListener( new ManagerChangeListener() );
//        pnlSingleDep.add();
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        pnlDeps = new javax.swing.JPanel();
        pnlSingleDep = new javax.swing.JPanel();
        pnlActions = new javax.swing.JPanel();
        btnDownload = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        pnlDeps.setLayout(new java.awt.GridBagLayout());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        add(pnlDeps, gridBagConstraints);

        pnlSingleDep.setLayout(new java.awt.BorderLayout());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.2;
        add(pnlSingleDep, gridBagConstraints);

        pnlActions.setLayout(new java.awt.GridBagLayout());

        btnDownload.setText("Download");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 0.1;
        pnlActions.add(btnDownload, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 0.2;
        add(pnlActions, gridBagConstraints);

    }//GEN-END:initComponents
    
    public ExplorerManager getExplorerManager() {
        return manager;
    }
    
    public void addNotify() {
        super.addNotify();
        manager.setRootContext(createRootNode());
        btv.expandAll();
        selectFirstNode();
    }
    
    private void selectFirstNode() {
        Children ch = manager.getRootContext().getChildren();
        if ( ch != null ) {
            Node nodes[] = ch.getNodes();
            
            if ( nodes != null && nodes.length > 0 ) {
                try {
                    manager.setSelectedNodes( new Node[] { nodes[0] } );
                }
                catch ( PropertyVetoException e ) {
                    // No node will be selected
                }
            }
        }
    }
    
    /** Listens to selection change and shows the customizers as
     *  panels
     */
    
    private class ManagerChangeListener implements PropertyChangeListener {
        
        public void propertyChange(PropertyChangeEvent evt) {
            if(evt.getSource() != manager) {
                return;
            }
            
            if (ExplorerManager.PROP_SELECTED_NODES.equals(evt.getPropertyName())) {
                Node nodes[] = manager.getSelectedNodes();
                if ( nodes == null || nodes.length <= 0 ) {
                    return;
                }
                Node node = nodes[0];
                
                if ( currentCustomizer != null ) {
                    pnlSingleDep.remove( currentCustomizer );
                }
                if ( node.hasCustomizer() ) {
                    currentCustomizer = (DependencyPanel)node.getCustomizer();
                    pnlSingleDep.add(currentCustomizer);
                    pnlSingleDep.validate();
                    pnlSingleDep.repaint();
                    
                }
                else {
                    currentCustomizer = null;
                }
                
                return;
            }
        }
    }
    
    private Node createRootNode() {
        Project mavproj = project.getOriginalMavenProject();
        Node root = new AbstractNode(new DepRootChildren(mavproj));
        root.setName("root invisible");
        return root;
    }
    
    private class DepRootChildren extends Children.Keys {
        private Project project;
        public DepRootChildren(Project proj) {
            super();
            project = proj;
        }
        
        public void addNotify() {
            List depend = project.getDependencies();
            if (depend != null) {
                setKeys(depend);
            } else {
                setKeys(Collections.EMPTY_LIST);
            }
            
        }
        
        public void removeNotify() {
            setKeys(Collections.EMPTY_LIST);
        }
        
        protected Node[] createNodes(Object obj) {
            return new Node[] { new DependencyNode((Dependency)obj, DependencyCustomizer.this.project)};
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDownload;
    private javax.swing.JPanel pnlActions;
    private javax.swing.JPanel pnlDeps;
    private javax.swing.JPanel pnlSingleDep;
    // End of variables declaration//GEN-END:variables
    
}
