/* ==========================================================================
 * Copyright 2003-2004 Mevenide Team
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 * =========================================================================
 */

package org.mevenide.netbeans.cargo;

import java.awt.Dimension;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import org.codehaus.cargo.container.Container;
import org.codehaus.cargo.container.configuration.ConfigurationFactory;
import org.codehaus.cargo.container.installer.Proxy;
import org.codehaus.cargo.container.installer.ZipURLInstaller;
import org.codehaus.cargo.container.property.ServletPropertySet;
import org.codehaus.cargo.util.monitor.SimpleMonitor;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.awt.StatusDisplayer;


/**
 *
 * @author  Milos Kleint (mkleint@codehaus.org)
 */
public class ContainerPanel extends javax.swing.JPanel {
    
    /** Creates new form ContainerPanel */
    public ContainerPanel() {
        initComponents();
        comType.setModel(new DefaultComboBoxModel(CargoServerRegistry.CONTAINER_TYPES));
        setPreferredSize(new Dimension(500, 150));
        cbExisting.setSelected(true);
        lblDownloadUrl.setVisible(false);
        txtDownloadUrl.setVisible(false);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblType = new javax.swing.JLabel();
        comType = new javax.swing.JComboBox();
        lblInstallDir = new javax.swing.JLabel();
        txtInstallDir = new javax.swing.JTextField();
        btnInstallDir = new javax.swing.JButton();
        cbStart = new javax.swing.JCheckBox();
        lblPort = new javax.swing.JLabel();
        txtPort = new javax.swing.JTextField();
        cbExisting = new javax.swing.JCheckBox();
        lblDownloadUrl = new javax.swing.JLabel();
        txtDownloadUrl = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setLayout(new java.awt.GridBagLayout());

        lblType.setText("Container Type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        add(lblType, gridBagConstraints);

        comType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comTypeActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        add(comType, gridBagConstraints);

        lblInstallDir.setText("Install Directory");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        add(lblInstallDir, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        add(txtInstallDir, gridBagConstraints);

        btnInstallDir.setText("Browse...");
        btnInstallDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstallDirActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(3, 6, 0, 6);
        add(btnInstallDir, gridBagConstraints);

        cbStart.setText("Start Immediately");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 0);
        add(cbStart, gridBagConstraints);

        lblPort.setText("Port");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        add(lblPort, gridBagConstraints);

        txtPort.setText("8080");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        add(txtPort, gridBagConstraints);

        cbExisting.setText("Use existing installation");
        cbExisting.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(0, 0, 0, 0)));
        cbExisting.setMargin(new java.awt.Insets(0, 0, 0, 0));
        cbExisting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbExistingActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        add(cbExisting, gridBagConstraints);

        lblDownloadUrl.setText("Download URL");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        add(lblDownloadUrl, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        add(txtDownloadUrl, gridBagConstraints);

        jPanel1.setMinimumSize(new java.awt.Dimension(10, 19));
        jPanel1.setPreferredSize(new java.awt.Dimension(10, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        add(jPanel1, gridBagConstraints);

    }
    // </editor-fold>//GEN-END:initComponents

    private void comTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comTypeActionPerformed
        if (!cbExisting.isSelected()) {
            txtDownloadUrl.setText(CargoServerRegistry.getInstance().getDownloadUrl((String)comType.getSelectedItem()));            
        } else {
            txtDownloadUrl.setText("");
        }
    }//GEN-LAST:event_comTypeActionPerformed

    private void cbExistingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbExistingActionPerformed
        lblDownloadUrl.setVisible(!cbExisting.isSelected());
        txtDownloadUrl.setVisible(!cbExisting.isSelected());
        if (!cbExisting.isSelected()) {
            txtDownloadUrl.setText(CargoServerRegistry.getInstance().getDownloadUrl((String)comType.getSelectedItem()));
        } else {
            txtDownloadUrl.setText("");
        }
    }//GEN-LAST:event_cbExistingActionPerformed

    private void btnInstallDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstallDirActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Select Container's Home Directory");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        String path = txtInstallDir.getText();
        if (path.length() > 0) {
            File f = new File(path);
            if (f.exists()) {
                chooser.setSelectedFile(f);
            }
        }
        if ( JFileChooser.APPROVE_OPTION == chooser.showOpenDialog(this)) { //NOI18N
            File projectDir = chooser.getSelectedFile();
            txtInstallDir.setText( projectDir.getAbsolutePath() );
        }

    }//GEN-LAST:event_btnInstallDirActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInstallDir;
    private javax.swing.JCheckBox cbExisting;
    private javax.swing.JCheckBox cbStart;
    private javax.swing.JComboBox comType;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDownloadUrl;
    private javax.swing.JLabel lblInstallDir;
    private javax.swing.JLabel lblPort;
    private javax.swing.JLabel lblType;
    private javax.swing.JTextField txtDownloadUrl;
    private javax.swing.JTextField txtInstallDir;
    private javax.swing.JTextField txtPort;
    // End of variables declaration//GEN-END:variables
    
    public void createContainer() {
        StatusDisplayer.getDefault().setStatusText("Creating new Cargo Container instance.");
        CargoServerRegistry reg = CargoServerRegistry.getInstance();
        Container cont = null;
        File homeDir = null;
        cont = reg.getFactory().createContainer((String)comType.getSelectedItem());
        if (cbExisting.isSelected()) {
            homeDir = new File(txtInstallDir.getText());
        } else {
            StatusDisplayer.getDefault().setStatusText("Downloading server binaries...");
            //download first
            try {
                URL url = new URL(txtDownloadUrl.getText());
                File dir = new File(txtInstallDir.getText());
                ZipURLInstaller installer = new ZipURLInstaller(url, dir);
                String host = ProxyUtilities.getProxyHost();
                String port = ProxyUtilities.getProxyPort();
                if (host != null && port != null && port.length() > 0 && host.length() > 0) {
                    Proxy proxy = new Proxy();
                    proxy.setHost(host);
                    proxy.setPort(Integer.parseInt(port));
                    installer.setProxy(proxy);
                }
                installer.setMonitor(new SimpleMonitor());
                installer.install();
                homeDir = installer.getHomeDir();
            } catch (MalformedURLException exc) {
                NotifyDescriptor nd = new NotifyDescriptor.Message("Malformed URL:" + exc.getLocalizedMessage());
                DialogDisplayer.getDefault().notify(nd);
                return;
            }
        }
         
        if (homeDir != null && homeDir.exists()) {
            cont.setHomeDir(homeDir);
            try {
                cont.setOutput(File.createTempFile(cont.getId(), "log"));
            } catch (IOException exc) {
                
            }
            cont.setConfiguration(reg.getConfigFactory().createConfiguration(cont, ConfigurationFactory.STANDALONE));
            cont.getConfiguration().setProperty(ServletPropertySet.PORT, txtPort.getText());
            CargoServerRegistry.getInstance().addContainer(cont);
            if (cbStart.isSelected()) {
                reg.startContainer(cont);
            }
            StatusDisplayer.getDefault().setStatusText("Installed Cargo container.");
        } else {
            NotifyDescriptor nd = new NotifyDescriptor.Message("Error");
            DialogDisplayer.getDefault().notify(nd);
        }
    }
}
