/* ==========================================================================
 * Copyright 2006 Mevenide Team
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 * =========================================================================
 */

package org.codehaus.mevenide.idea.gui.form;

import com.intellij.openapi.projectRoots.ProjectJdk;
import com.intellij.openapi.projectRoots.ProjectJdkTable;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import org.apache.commons.lang.StringUtils;
import org.codehaus.mevenide.idea.common.MavenBuildPluginSettings;
import org.codehaus.mevenide.idea.form.CustomizingObject;
import org.codehaus.mevenide.idea.helper.IForm;

import javax.swing.*;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.*;

/**
 * Creates the form for the Maven2 build setup and is responsible for updating the
 * underlying data model.
 *
 * @author Ralf Quebbemann (ralfq@codehaus.org)
 */
public class MavenBuildConfigurationForm implements IForm {
    /**
     * Field description
     */
    public static final String ACTION_COMMAND_SET_MAVEN_HOME = "Set Maven Home";

    /**
     * Field description
     */
    public static final String ACTION_COMMAND_SET_JDK_HOME = "Set JDK Home";

    private JCheckBox checkBoxUseEmbeddedMaven;
    private JPanel panel;
    private JTextField textFieldMavenHomeDirectory;
    private JButton buttonBrowseMavenHomeDirectory;
    private JTextField textFieldVMParameters;
    private JCheckBox checkBoxSkipTests;
    private JLabel labelBrowseMavenHomeDirectory;
    private JLabel labelJdkHomeDirectory;
    private JLabel labelVMParameters;
    private JComboBox comboBoxChooseJDK;
    private JTable tableProperties;
    private DefaultTableModel tablePropertiesModel;
    private JScrollPane scrollPaneProperties;
    private JCheckBox checkBoxRunMavenInBackground;
    private DefaultComboBoxModel comboboxModelModelChooseJdk = new DefaultComboBoxModel();
    private MavenBuildConfigurationTableListener propertiesTableListener;


    public MavenBuildConfigurationForm() {
        Vector<Vector> tablePropertiesData = new Vector<Vector>();
        buttonBrowseMavenHomeDirectory.setActionCommand(ACTION_COMMAND_SET_MAVEN_HOME);
        Vector<String> columnNames = new Vector<String>();
        columnNames.add("Property Key");
        columnNames.add("Property Value");
        tablePropertiesModel = new DefaultTableModel(tablePropertiesData, columnNames);
        tableProperties.setModel(tablePropertiesModel);
        tableProperties.setPreferredSize(null);
        tableProperties.setPreferredScrollableViewportSize(null);
        scrollPaneProperties.setPreferredSize(new Dimension(250, 100));

        getButtonBrowseMavenHomeDirectory().addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                JFileChooser fileChooser = new JFileChooser();
                fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

                String path = textFieldMavenHomeDirectory.getText();
                if (!StringUtils.isEmpty(path)) {
                    fileChooser.setCurrentDirectory(new File(path));
                }

                if (fileChooser.showOpenDialog(getRootComponent()) == JFileChooser.APPROVE_OPTION) {
                    textFieldMavenHomeDirectory.setText(fileChooser.getSelectedFile().getPath());
                }
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new FormLayout("fill:d:grow",
                "center:d:grow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:d:grow,top:4dlu:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:d:noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow",
                "center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,top:max(d;4px):noGrow"));
        CellConstraints cc = new CellConstraints();
        panel.add(panel1, cc.xy(1, 1, CellConstraints.FILL, CellConstraints.FILL));
        panel1.setBorder(BorderFactory.createTitledBorder("Maven Build Setup"));
        textFieldMavenHomeDirectory = new JTextField();
        textFieldMavenHomeDirectory.setColumns(25);
        textFieldMavenHomeDirectory.setEnabled(false);
        textFieldMavenHomeDirectory.setText("");
        panel1.add(textFieldMavenHomeDirectory, cc.xy(1, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        labelBrowseMavenHomeDirectory = new JLabel();
        labelBrowseMavenHomeDirectory.setEnabled(false);
        labelBrowseMavenHomeDirectory.setText("Maven2 Home Directory");
        panel1.add(labelBrowseMavenHomeDirectory, cc.xy(1, 3));
        buttonBrowseMavenHomeDirectory = new JButton();
        buttonBrowseMavenHomeDirectory.setEnabled(false);
        buttonBrowseMavenHomeDirectory.setText("Browse ...");
        panel1.add(buttonBrowseMavenHomeDirectory, cc.xy(3, 5, CellConstraints.LEFT, CellConstraints.DEFAULT));
        labelJdkHomeDirectory = new JLabel();
        labelJdkHomeDirectory.setEnabled(false);
        labelJdkHomeDirectory.setText("Choose JDK");
        panel1.add(labelJdkHomeDirectory, cc.xy(1, 7));
        labelVMParameters = new JLabel();
        labelVMParameters.setEnabled(false);
        labelVMParameters.setText("VM Parameters");
        panel1.add(labelVMParameters, cc.xy(1, 11));
        textFieldVMParameters = new JTextField();
        textFieldVMParameters.setEnabled(false);
        panel1.add(textFieldVMParameters, cc.xy(1, 13, CellConstraints.FILL, CellConstraints.DEFAULT));
        comboBoxChooseJDK = new JComboBox();
        comboBoxChooseJDK.setPreferredSize(new Dimension(150, 24));
        panel1.add(comboBoxChooseJDK, cc.xy(1, 9, CellConstraints.LEFT, CellConstraints.DEFAULT));
        checkBoxUseEmbeddedMaven = new JCheckBox();
        checkBoxUseEmbeddedMaven.setSelected(true);
        checkBoxUseEmbeddedMaven.setText("Use Embedded Maven");
        panel1.add(checkBoxUseEmbeddedMaven, cc.xy(1, 1));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FormLayout("fill:d:noGrow", "top:d:noGrow"));
        panel.add(panel2, cc.xy(1, 3, CellConstraints.FILL, CellConstraints.FILL));
        panel2.setBorder(BorderFactory.createTitledBorder("Options"));
        checkBoxSkipTests = new JCheckBox();
        checkBoxSkipTests.setText("Skip Tests");
        panel2.add(checkBoxSkipTests, cc.xy(1, 1));
        scrollPaneProperties = new JScrollPane();
        scrollPaneProperties.setHorizontalScrollBarPolicy(31);
        scrollPaneProperties.setPreferredSize(new Dimension(0, 100));
        scrollPaneProperties.setVerifyInputWhenFocusTarget(false);
        scrollPaneProperties.setVerticalScrollBarPolicy(20);
        panel.add(scrollPaneProperties, cc.xy(1, 5, CellConstraints.FILL, CellConstraints.FILL));
        scrollPaneProperties.setBorder(BorderFactory.createTitledBorder("Properties"));
        tableProperties = new JTable();
        tableProperties.setPreferredScrollableViewportSize(new Dimension(0, 0));
        tableProperties.setPreferredSize(new Dimension(200, 0));
        scrollPaneProperties.setViewportView(tableProperties);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

    class MavenBuildConfigurationTableListener implements TableModelListener {
        public void tableChanged(TableModelEvent tableModelEvent) {
            if (tablePropertiesModel.getRowCount() > 0) {
                int changedRow = tableModelEvent.getLastRow();
                if ((changedRow == tablePropertiesModel.getRowCount() - 1) &&
                        (!isRowEmpty(changedRow))) {
                    addEmptyPropertyRow();
                    return;
                }
                if ((isRowEmpty(changedRow)) &&
                        (tablePropertiesModel.getRowCount() > 1) &&
                        (changedRow != tablePropertiesModel.getRowCount() - 1)) {
                    tablePropertiesModel.removeRow(changedRow);
                }
            }
        }
    }

    private void addEmptyPropertyRow() {
        Vector<String> emptyPropertyRow = new Vector<String>();
        emptyPropertyRow.add("");
        emptyPropertyRow.add("");
        tablePropertiesModel.addRow(emptyPropertyRow);
    }

    private boolean hasEmptyLastRow() {
        Vector<Vector> tablePropertiesData = tablePropertiesModel.getDataVector();
        if (tablePropertiesData.size() > 0) {
            Vector lastRow = tablePropertiesData.elementAt(tablePropertiesData.size() - 1);
            String lastKey = (String) lastRow.elementAt(0);
            String lastValue = (String) lastRow.elementAt(1);
            if (StringUtils.isEmpty(lastKey)) {
                return true;
            }
        }
        return false;
    }

    private boolean isRowEmpty(int row) {
        Vector<Vector> tablePropertiesData = tablePropertiesModel.getDataVector();
        if (tablePropertiesData.size() > 0) {
            Vector myRow = tablePropertiesData.elementAt(row);
            String lastKey = (String) myRow.elementAt(0);
            String lastValue = (String) myRow.elementAt(1);
            if (StringUtils.isEmpty(lastKey) && StringUtils.isEmpty(lastValue)) {
                return true;
            }
        }
        return false;
    }

    private void fillComboboxJdk() {
        ProjectJdkTable jdkTable = ProjectJdkTable.getInstance();
        ProjectJdk[] projectJdks = jdkTable.getAllJdks();
        comboboxModelModelChooseJdk.removeAllElements();
        for (ProjectJdk projectJdk : projectJdks) {
            comboboxModelModelChooseJdk
                    .addElement(
                            new CustomizingObject(projectJdk.getVMExecutablePath(), projectJdk.getName()));
        }
        comboboxModelModelChooseJdk.addElement(new CustomizingObject("", "Use $JAVA_HOME"));
        comboBoxChooseJDK.setModel(comboboxModelModelChooseJdk);
    }

    public JTextField getTextFieldMavenHomeDirectory() {
        return textFieldMavenHomeDirectory;
    }

    public JButton getButtonBrowseMavenHomeDirectory() {
        return buttonBrowseMavenHomeDirectory;
    }

    public JComponent getRootComponent() {
        return panel;
    }

    public void setData(MavenBuildPluginSettings data) {
        tablePropertiesModel.removeTableModelListener(propertiesTableListener);
        fillComboboxJdk();
        for (int i = 0; i < comboboxModelModelChooseJdk.getSize(); i++) {
            CustomizingObject customizingObject = (CustomizingObject) comboboxModelModelChooseJdk.getElementAt(i);
            if (customizingObject.getValue().equals(data.getJdkPath())) {
                comboBoxChooseJDK.setSelectedItem(customizingObject);
                break;
            } else if (StringUtils.isBlank(customizingObject.getValue())) {
                comboBoxChooseJDK.setSelectedItem(customizingObject);
            }
        }

        checkBoxUseEmbeddedMaven.setSelected(data.isUseMavenEmbedder());
        checkBoxRunMavenInBackground.setSelected(data.isRunMavenInBackground());
        textFieldMavenHomeDirectory.setText(data.getMavenHome());
        textFieldVMParameters.setText(data.getVmOptions());
        checkBoxSkipTests.setSelected(data.isSkipTests());
        Map<String, String> mavenProperties = data.getMavenProperties();
        tablePropertiesModel.getDataVector().clear();
        for (int i = 0; i < tablePropertiesModel.getRowCount(); i++) {
            tablePropertiesModel.removeRow(i);
        }
        Set keys = mavenProperties.keySet();
        for (Object key : keys) {
            String propertyKey = (String) key;
            String propertyValue = mavenProperties.get(propertyKey);
            if (StringUtils.isEmpty(propertyKey)) {
                continue;
            }
            Vector<String> rowData = new Vector<String>();
            rowData.add(propertyKey);
            rowData.add(propertyValue);
            tablePropertiesModel.addRow(rowData);
        }

        if (!hasEmptyLastRow()) {
            addEmptyPropertyRow();
        }
        // register listener for table change events.
        propertiesTableListener = new MavenBuildConfigurationTableListener();
        tablePropertiesModel.addTableModelListener(propertiesTableListener);
    }

    public void getData(MavenBuildPluginSettings data) {
        data.setUseMavenEmbedder(checkBoxUseEmbeddedMaven.isSelected());
        data.setRunMavenInBackground(checkBoxRunMavenInBackground.isSelected());
        data.setMavenHome(textFieldMavenHomeDirectory.getText());
        data.setVmOptions(textFieldVMParameters.getText());
        data.setSkipTests(checkBoxSkipTests.isSelected());
        data.setJdkPath(((CustomizingObject) comboBoxChooseJDK.getSelectedItem()).getValue());
        Vector<Vector> tableDataVector = tablePropertiesModel.getDataVector();
        data.getMavenProperties().clear();
        for (Vector aDataRow : tableDataVector) {
            if (StringUtils.isEmpty((String) aDataRow.elementAt(0))) {
                continue;
            }
            data.getMavenProperties().put((String) aDataRow.elementAt(0), (String) aDataRow.elementAt(1));
        }
    }

    public boolean isModified(MavenBuildPluginSettings data) {
        if (!checkBoxUseEmbeddedMaven.isSelected()) {
            textFieldMavenHomeDirectory.setEnabled(true);
            textFieldVMParameters.setEnabled(true);
            buttonBrowseMavenHomeDirectory.setEnabled(true);
            labelBrowseMavenHomeDirectory.setEnabled(true);
            labelJdkHomeDirectory.setEnabled(true);
            labelVMParameters.setEnabled(true);
            comboBoxChooseJDK.setEnabled(true);
        } else {
            textFieldMavenHomeDirectory.setEnabled(false);
            textFieldVMParameters.setEnabled(false);
            buttonBrowseMavenHomeDirectory.setEnabled(false);
            labelBrowseMavenHomeDirectory.setEnabled(false);
            labelJdkHomeDirectory.setEnabled(false);
            labelVMParameters.setEnabled(false);
            comboBoxChooseJDK.setEnabled(false);
        }
        if (checkBoxUseEmbeddedMaven.isSelected() != data.isUseMavenEmbedder()) return true;
        if (checkBoxRunMavenInBackground.isSelected() != data.isRunMavenInBackground()) return true;
        if (textFieldMavenHomeDirectory.getText() != null ?
                !textFieldMavenHomeDirectory.getText().equals(data.getMavenHome()) : data.getMavenHome() != null)
            return true;
        if (textFieldVMParameters.getText() != null ? !textFieldVMParameters.getText().equals(data.getVmOptions()) :
                data.getVmOptions() != null) return true;
        if (checkBoxSkipTests.isSelected() != data.isSkipTests()) return true;
        if (!((CustomizingObject) comboBoxChooseJDK.getSelectedItem()).getValue()
                .equals(data.getJdkPath()))
            return true;

        if (hasMavenPropertiesChanged(data)) {
            return true;
        }
        return false;
    }

    /**
     * Checks whether the properties in the current table are different from those stored in the model.
     * The properties are different if the size of both properties object is different or one Properties
     * contains a key which is not in the other Properties object or a value from a key in one Properties
     * object is different from a value of the other Properties object.
     *
     * @param data The data model.
     * @return if and only if both properties object are not holding the same properties.
     */
    private boolean hasMavenPropertiesChanged(MavenBuildPluginSettings data) {
        Properties tableDataProperties = new Properties();
        Vector<Vector> tableDataVector = tablePropertiesModel.getDataVector();
        for (Vector aDataRow : tableDataVector) {
            if (StringUtils.isEmpty((String) aDataRow.elementAt(0))) {
                continue;
            }
            tableDataProperties.setProperty((String) aDataRow.elementAt(0), (String) aDataRow.elementAt(1));
        }
        if (tableDataProperties.size() != data.getMavenProperties().size()) {
            return true;
        } else {
            Enumeration keys = tableDataProperties.keys();
            while (keys.hasMoreElements()) {
                String key = (String) keys.nextElement();
                String value = tableDataProperties.getProperty(key);
                if (data.getMavenProperties().containsKey(key)) {
                    String dataValue = data.getMavenProperties().get(key);
                    if (!value.equals(dataValue)) {
                        return true;
                    }
                } else {
                    return true;
                }
            }
        }
        return false;
    }

}
