/* ==========================================================================
 * Copyright 2003-2004 Mevenide Team
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 * =========================================================================
 */
package org.mevenide.netbeans.project.customizer;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;

import java.util.List;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextField;
import org.mevenide.netbeans.project.ActionProviderImpl;
import org.mevenide.netbeans.project.MavenProject;
import org.mevenide.netbeans.project.customizer.ui.LocationComboFactory;
import org.mevenide.netbeans.project.customizer.ui.OriginChange;
import org.mevenide.netbeans.project.exec.CustomGoalsPanel;
import org.mevenide.netbeans.project.goals.GoalUtils;
import org.mevenide.netbeans.project.goals.GoalsGrabberProvider;
import org.mevenide.properties.IPropertyLocator;
import org.netbeans.spi.project.ActionProvider;
import org.openide.DialogDescriptor;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;



/**
 *
 * @author  Milos Kleint (ca206216@tiscali.cz)
 */
public class ActionMappingPanel extends JPanel implements ProjectPanel {
    
    private ProjectValidateObserver valObserver;
    private MavenProject project;
    
    private OriginChange ocBuild;
    private OriginChange ocClean;    
    private OriginChange ocJavadoc;    
    private OriginChange ocRebuild;    
    private OriginChange ocTest;    
    private OriginChange ocTestSingle;
    private OriginChange ocDebugTestSingle;
    private OriginChange ocMultiBuild;
    private OriginChange ocMultiClean;
    private OriginChange ocRun;
    private OriginChange ocRunSingle;
    private OriginChange ocDebug;
    private OriginChange ocDebugSingle;
    
    private HashMap changes;
    
    /** Creates new form BasicsPanel */
    public ActionMappingPanel(MavenProject proj) {
        project = proj;
        changes = new HashMap();
        initComponents();
        valObserver = null;
        setName("Goal-IDE Action Mapping");

        attachBrowseListeners();
        populateChangeInstances();
    }
    
    private void setEnableBrowseFields(boolean enable) {
        btnBuildBrowse.setEnabled(enable);
        btnCleanBrowse.setEnabled(enable);
        btnRebuildBrowse.setEnabled(enable);
        btnJavadocBrowse.setEnabled(enable);
        btnDebugBrowse.setEnabled(enable);
        btnDebugSingleBrowse.setEnabled(enable);
        btnRunBrowse.setEnabled(enable);
        btnRunSingleBrowse.setEnabled(enable);
        btnTestBrowse.setEnabled(enable);
        btnTestSingleBrowse.setEnabled(enable);
        btnDebugTestSingleBrowse.setEnabled(enable);
        btnMultiBuildBrowse.setEnabled(enable);
        btnMultiCleanBrowse.setEnabled(enable);
    }
    
    private void attachBrowseListeners() {
        btnBuildBrowse.addActionListener(new GoalsListener(txtBuild));
        btnCleanBrowse.addActionListener(new GoalsListener(txtClean));
        btnRebuildBrowse.addActionListener(new GoalsListener(txtRebuild));
        btnJavadocBrowse.addActionListener(new GoalsListener(txtJavadoc));
        btnDebugBrowse.addActionListener(new GoalsListener(txtDebug));
        btnDebugSingleBrowse.addActionListener(new GoalsListener(txtDebugSingle));
        btnDebugTestSingleBrowse.addActionListener(new GoalsListener(txtDebugTestSingle));
        btnRunBrowse.addActionListener(new GoalsListener(txtRun));
        btnRunSingleBrowse.addActionListener(new GoalsListener(txtRunSingle));
        btnTestBrowse.addActionListener(new GoalsListener(txtTest));
        btnTestSingleBrowse.addActionListener(new GoalsListener(txtTestSingle));
        btnMultiCleanBrowse.addActionListener(new GoalsListener(txtMultiClean));
        btnMultiBuildBrowse.addActionListener(new GoalsListener(txtMultiBuild));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        lblBuild = new javax.swing.JLabel();
        txtBuild = new javax.swing.JTextField();
        btnBuildBrowse = new javax.swing.JButton();
        ocBuild = LocationComboFactory.createPropertiesChange(project);
        btnBuild = (JButton)ocBuild.getComponent();
        lblClean = new javax.swing.JLabel();
        txtClean = new javax.swing.JTextField();
        btnCleanBrowse = new javax.swing.JButton();
        ocClean = LocationComboFactory.createPropertiesChange(project);
        btnClean = (JButton)ocClean.getComponent();
        lblRebuild = new javax.swing.JLabel();
        txtRebuild = new javax.swing.JTextField();
        btnRebuildBrowse = new javax.swing.JButton();
        ocRebuild = LocationComboFactory.createPropertiesChange(project);
        btnRebuild = (JButton)ocRebuild.getComponent();
        lblJavadoc = new javax.swing.JLabel();
        txtJavadoc = new javax.swing.JTextField();
        btnJavadocBrowse = new javax.swing.JButton();
        ocJavadoc = LocationComboFactory.createPropertiesChange(project);
        btnJavadoc = (JButton)ocJavadoc.getComponent();
        lblRun = new javax.swing.JLabel();
        txtRun = new javax.swing.JTextField();
        btnRunBrowse = new javax.swing.JButton();
        ocRun = LocationComboFactory.createPropertiesChange(project);
        btnRun = (JButton)ocRun.getComponent();
        lblRunSingle = new javax.swing.JLabel();
        txtRunSingle = new javax.swing.JTextField();
        btnRunSingleBrowse = new javax.swing.JButton();
        ocRunSingle = LocationComboFactory.createPropertiesChange(project);
        btnRunSingle = (JButton)ocRunSingle.getComponent();
        lblDebug = new javax.swing.JLabel();
        txtDebug = new javax.swing.JTextField();
        btnDebugBrowse = new javax.swing.JButton();
        ocDebug = LocationComboFactory.createPropertiesChange(project);
        btnDebug = (JButton)ocDebug.getComponent();
        lblDebugSingle = new javax.swing.JLabel();
        txtDebugSingle = new javax.swing.JTextField();
        btnDebugSingleBrowse = new javax.swing.JButton();
        ocDebugSingle = LocationComboFactory.createPropertiesChange(project);
        btnDebugSingle = (JButton)ocDebugSingle.getComponent();
        lblTest = new javax.swing.JLabel();
        txtTest = new javax.swing.JTextField();
        btnTestBrowse = new javax.swing.JButton();
        ocTest = LocationComboFactory.createPropertiesChange(project);
        btnTest = (JButton)ocTest.getComponent();
        lblTestSingle = new javax.swing.JLabel();
        txtTestSingle = new javax.swing.JTextField();
        btnTestSingleBrowse = new javax.swing.JButton();
        ocTestSingle = LocationComboFactory.createPropertiesChange(project);
        btnTestSingle = (JButton)ocTestSingle.getComponent();
        lblDebugTestSingle = new javax.swing.JLabel();
        txtDebugTestSingle = new javax.swing.JTextField();
        btnDebugTestSingleBrowse = new javax.swing.JButton();
        ocDebugTestSingle = LocationComboFactory.createPropertiesChange(project);
        btnDebugTestSingle = (JButton)ocDebugTestSingle.getComponent();
        lblMultiBuild = new javax.swing.JLabel();
        txtMultiBuild = new javax.swing.JTextField();
        btnMultiBuildBrowse = new javax.swing.JButton();
        ocMultiBuild = LocationComboFactory.createPropertiesChange(project);
        btnMultiBuild = (JButton)ocMultiBuild.getComponent();
        lblMultiClean = new javax.swing.JLabel();
        txtMultiClean = new javax.swing.JTextField();
        btnMultiCleanBrowse = new javax.swing.JButton();
        ocMultiClean = LocationComboFactory.createPropertiesChange(project);
        btnMultiClean = (JButton)ocMultiClean.getComponent();
        jPanel1 = new javax.swing.JPanel();

        setLayout(new java.awt.GridBagLayout());

        lblBuild.setLabelFor(txtBuild);
        lblBuild.setText("Build :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 0);
        add(lblBuild, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(txtBuild, gridBagConstraints);

        btnBuildBrowse.setText("...");
        btnBuildBrowse.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btnBuildBrowse.setMaximumSize(new java.awt.Dimension(20, 16));
        btnBuildBrowse.setMinimumSize(new java.awt.Dimension(20, 16));
        btnBuildBrowse.setPreferredSize(new java.awt.Dimension(20, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(btnBuildBrowse, gridBagConstraints);

        btnBuild.setPreferredSize(new java.awt.Dimension(16, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(btnBuild, gridBagConstraints);

        lblClean.setLabelFor(txtClean);
        lblClean.setText("Clean :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 0);
        add(lblClean, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(txtClean, gridBagConstraints);

        btnCleanBrowse.setText("...");
        btnCleanBrowse.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btnCleanBrowse.setMaximumSize(new java.awt.Dimension(20, 16));
        btnCleanBrowse.setMinimumSize(new java.awt.Dimension(20, 16));
        btnCleanBrowse.setPreferredSize(new java.awt.Dimension(20, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(btnCleanBrowse, gridBagConstraints);

        btnClean.setPreferredSize(new java.awt.Dimension(16, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(btnClean, gridBagConstraints);

        lblRebuild.setLabelFor(txtRebuild);
        lblRebuild.setText("Rebuild :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 0);
        add(lblRebuild, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(txtRebuild, gridBagConstraints);

        btnRebuildBrowse.setText("...");
        btnRebuildBrowse.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btnRebuildBrowse.setMaximumSize(new java.awt.Dimension(20, 16));
        btnRebuildBrowse.setMinimumSize(new java.awt.Dimension(20, 16));
        btnRebuildBrowse.setPreferredSize(new java.awt.Dimension(20, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(btnRebuildBrowse, gridBagConstraints);

        btnRebuild.setPreferredSize(new java.awt.Dimension(16, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(btnRebuild, gridBagConstraints);

        lblJavadoc.setLabelFor(txtJavadoc);
        lblJavadoc.setText("Javadoc :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 0);
        add(lblJavadoc, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(txtJavadoc, gridBagConstraints);

        btnJavadocBrowse.setText("...");
        btnJavadocBrowse.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btnJavadocBrowse.setMaximumSize(new java.awt.Dimension(20, 16));
        btnJavadocBrowse.setMinimumSize(new java.awt.Dimension(20, 16));
        btnJavadocBrowse.setPreferredSize(new java.awt.Dimension(20, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(btnJavadocBrowse, gridBagConstraints);

        btnJavadoc.setPreferredSize(new java.awt.Dimension(16, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(btnJavadoc, gridBagConstraints);

        lblRun.setLabelFor(txtRun);
        lblRun.setText("Run :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 0);
        add(lblRun, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(txtRun, gridBagConstraints);

        btnRunBrowse.setText("...");
        btnRunBrowse.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btnRunBrowse.setMaximumSize(new java.awt.Dimension(20, 16));
        btnRunBrowse.setMinimumSize(new java.awt.Dimension(20, 16));
        btnRunBrowse.setPreferredSize(new java.awt.Dimension(20, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(btnRunBrowse, gridBagConstraints);

        btnRun.setPreferredSize(new java.awt.Dimension(16, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(btnRun, gridBagConstraints);

        lblRunSingle.setLabelFor(txtRunSingle);
        lblRunSingle.setText("Run Single :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 0);
        add(lblRunSingle, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(txtRunSingle, gridBagConstraints);

        btnRunSingleBrowse.setText("...");
        btnRunSingleBrowse.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btnRunSingleBrowse.setMaximumSize(new java.awt.Dimension(20, 16));
        btnRunSingleBrowse.setMinimumSize(new java.awt.Dimension(20, 16));
        btnRunSingleBrowse.setPreferredSize(new java.awt.Dimension(20, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(btnRunSingleBrowse, gridBagConstraints);

        btnRunSingle.setPreferredSize(new java.awt.Dimension(16, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(btnRunSingle, gridBagConstraints);

        lblDebug.setLabelFor(txtDebug);
        lblDebug.setText("Debug :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 0);
        add(lblDebug, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(txtDebug, gridBagConstraints);

        btnDebugBrowse.setText("...");
        btnDebugBrowse.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btnDebugBrowse.setMaximumSize(new java.awt.Dimension(20, 16));
        btnDebugBrowse.setMinimumSize(new java.awt.Dimension(20, 16));
        btnDebugBrowse.setPreferredSize(new java.awt.Dimension(20, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(btnDebugBrowse, gridBagConstraints);

        btnDebug.setPreferredSize(new java.awt.Dimension(16, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(btnDebug, gridBagConstraints);

        lblDebugSingle.setLabelFor(txtDebugSingle);
        lblDebugSingle.setText("Debug Single :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 0);
        add(lblDebugSingle, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(txtDebugSingle, gridBagConstraints);

        btnDebugSingleBrowse.setText("...");
        btnDebugSingleBrowse.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btnDebugSingleBrowse.setMaximumSize(new java.awt.Dimension(20, 16));
        btnDebugSingleBrowse.setMinimumSize(new java.awt.Dimension(20, 16));
        btnDebugSingleBrowse.setPreferredSize(new java.awt.Dimension(20, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(btnDebugSingleBrowse, gridBagConstraints);

        btnDebugSingle.setPreferredSize(new java.awt.Dimension(16, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(btnDebugSingle, gridBagConstraints);

        lblTest.setLabelFor(txtTest);
        lblTest.setText("Test :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 0);
        add(lblTest, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(txtTest, gridBagConstraints);

        btnTestBrowse.setText("...");
        btnTestBrowse.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btnTestBrowse.setMaximumSize(new java.awt.Dimension(20, 16));
        btnTestBrowse.setMinimumSize(new java.awt.Dimension(20, 16));
        btnTestBrowse.setPreferredSize(new java.awt.Dimension(20, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(btnTestBrowse, gridBagConstraints);

        btnTest.setPreferredSize(new java.awt.Dimension(16, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(btnTest, gridBagConstraints);

        lblTestSingle.setLabelFor(txtTestSingle);
        lblTestSingle.setText("Test Single :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 0);
        add(lblTestSingle, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(txtTestSingle, gridBagConstraints);

        btnTestSingleBrowse.setText("...");
        btnTestSingleBrowse.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btnTestSingleBrowse.setMaximumSize(new java.awt.Dimension(20, 16));
        btnTestSingleBrowse.setMinimumSize(new java.awt.Dimension(20, 16));
        btnTestSingleBrowse.setPreferredSize(new java.awt.Dimension(20, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(btnTestSingleBrowse, gridBagConstraints);

        btnTestSingle.setPreferredSize(new java.awt.Dimension(16, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(btnTestSingle, gridBagConstraints);

        lblDebugTestSingle.setLabelFor(txtDebugTestSingle);
        lblDebugTestSingle.setText("Debug Test Single :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 0);
        add(lblDebugTestSingle, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(txtDebugTestSingle, gridBagConstraints);

        btnDebugTestSingleBrowse.setText("...");
        btnDebugTestSingleBrowse.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btnDebugTestSingleBrowse.setMaximumSize(new java.awt.Dimension(20, 16));
        btnDebugTestSingleBrowse.setMinimumSize(new java.awt.Dimension(20, 16));
        btnDebugTestSingleBrowse.setPreferredSize(new java.awt.Dimension(20, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(btnDebugTestSingleBrowse, gridBagConstraints);

        btnDebugTestSingle.setPreferredSize(new java.awt.Dimension(16, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(btnDebugTestSingle, gridBagConstraints);

        lblMultiBuild.setLabelFor(txtMultiBuild);
        lblMultiBuild.setText("Multi Project Build :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 0);
        add(lblMultiBuild, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(txtMultiBuild, gridBagConstraints);

        btnMultiBuildBrowse.setText("...");
        btnMultiBuildBrowse.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btnMultiBuildBrowse.setMaximumSize(new java.awt.Dimension(20, 16));
        btnMultiBuildBrowse.setMinimumSize(new java.awt.Dimension(20, 16));
        btnMultiBuildBrowse.setPreferredSize(new java.awt.Dimension(20, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(btnMultiBuildBrowse, gridBagConstraints);

        btnMultiBuild.setPreferredSize(new java.awt.Dimension(16, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(btnMultiBuild, gridBagConstraints);

        lblMultiClean.setLabelFor(txtMultiClean);
        lblMultiClean.setText("Multi Project Clean :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 0);
        add(lblMultiClean, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(txtMultiClean, gridBagConstraints);

        btnMultiCleanBrowse.setText("...");
        btnMultiCleanBrowse.setMargin(new java.awt.Insets(0, 2, 0, 2));
        btnMultiCleanBrowse.setMaximumSize(new java.awt.Dimension(20, 16));
        btnMultiCleanBrowse.setMinimumSize(new java.awt.Dimension(20, 16));
        btnMultiCleanBrowse.setPreferredSize(new java.awt.Dimension(20, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(btnMultiCleanBrowse, gridBagConstraints);

        btnMultiClean.setPreferredSize(new java.awt.Dimension(16, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 6, 0, 0);
        add(btnMultiClean, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 0.1;
        add(jPanel1, gridBagConstraints);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuild;
    private javax.swing.JButton btnBuildBrowse;
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnCleanBrowse;
    private javax.swing.JButton btnDebug;
    private javax.swing.JButton btnDebugBrowse;
    private javax.swing.JButton btnDebugSingle;
    private javax.swing.JButton btnDebugSingleBrowse;
    private javax.swing.JButton btnDebugTestSingle;
    private javax.swing.JButton btnDebugTestSingleBrowse;
    private javax.swing.JButton btnJavadoc;
    private javax.swing.JButton btnJavadocBrowse;
    private javax.swing.JButton btnMultiBuild;
    private javax.swing.JButton btnMultiBuildBrowse;
    private javax.swing.JButton btnMultiClean;
    private javax.swing.JButton btnMultiCleanBrowse;
    private javax.swing.JButton btnRebuild;
    private javax.swing.JButton btnRebuildBrowse;
    private javax.swing.JButton btnRun;
    private javax.swing.JButton btnRunBrowse;
    private javax.swing.JButton btnRunSingle;
    private javax.swing.JButton btnRunSingleBrowse;
    private javax.swing.JButton btnTest;
    private javax.swing.JButton btnTestBrowse;
    private javax.swing.JButton btnTestSingle;
    private javax.swing.JButton btnTestSingleBrowse;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBuild;
    private javax.swing.JLabel lblClean;
    private javax.swing.JLabel lblDebug;
    private javax.swing.JLabel lblDebugSingle;
    private javax.swing.JLabel lblDebugTestSingle;
    private javax.swing.JLabel lblJavadoc;
    private javax.swing.JLabel lblMultiBuild;
    private javax.swing.JLabel lblMultiClean;
    private javax.swing.JLabel lblRebuild;
    private javax.swing.JLabel lblRun;
    private javax.swing.JLabel lblRunSingle;
    private javax.swing.JLabel lblTest;
    private javax.swing.JLabel lblTestSingle;
    private javax.swing.JTextField txtBuild;
    private javax.swing.JTextField txtClean;
    private javax.swing.JTextField txtDebug;
    private javax.swing.JTextField txtDebugSingle;
    private javax.swing.JTextField txtDebugTestSingle;
    private javax.swing.JTextField txtJavadoc;
    private javax.swing.JTextField txtMultiBuild;
    private javax.swing.JTextField txtMultiClean;
    private javax.swing.JTextField txtRebuild;
    private javax.swing.JTextField txtRun;
    private javax.swing.JTextField txtRunSingle;
    private javax.swing.JTextField txtTest;
    private javax.swing.JTextField txtTestSingle;
    // End of variables declaration//GEN-END:variables
    
   private void populateChangeInstances() {
        createChangeInstance(ActionProvider.COMMAND_BUILD, txtBuild, ocBuild);
        createChangeInstance(ActionProvider.COMMAND_CLEAN, txtClean, ocClean);
        createChangeInstance(ActionProvider.COMMAND_REBUILD, txtRebuild, ocRebuild);
        createChangeInstance("javadoc", txtJavadoc, ocJavadoc); //NOI18N
        createChangeInstance(ActionProvider.COMMAND_RUN, txtRun, ocRun);
        createChangeInstance(ActionProvider.COMMAND_RUN_SINGLE, txtRunSingle, ocRunSingle);
        createChangeInstance(ActionProvider.COMMAND_DEBUG, txtDebug, ocDebug);
        createChangeInstance(ActionProvider.COMMAND_DEBUG_SINGLE, txtDebugSingle, ocDebugSingle);
        createChangeInstance(ActionProvider.COMMAND_TEST, txtTest, ocTest);
        createChangeInstance(ActionProvider.COMMAND_TEST_SINGLE, txtTestSingle, ocTestSingle);
        createChangeInstance(ActionProvider.COMMAND_DEBUG_TEST_SINGLE, txtDebugTestSingle, ocDebugTestSingle);
        createChangeInstance(ActionProviderImpl.COMMAND_MULTIPROJECTBUILD, txtMultiBuild, ocMultiBuild);
        createChangeInstance(ActionProviderImpl.COMMAND_MULTIPROJECTCLEAN, txtMultiClean, ocMultiClean);
   }
   
   private void createChangeInstance(String actionName, JTextField field, OriginChange oc) {
       String key = "maven.netbeans.exec." + actionName; //NOI18N
       String value = project.getPropertyResolver().getValue(key);
       int location = project.getPropertyLocator().getPropertyLocation(key);
       String defaultValue = ActionProviderImpl.getDefaultGoalForAction(key);
       if (value == null) {
           value = defaultValue;
           location = IPropertyLocator.LOCATION_DEFAULTS;
       } 
       changes.put(key, new TextFieldPropertyChange(key, value, location, field, oc, defaultValue));
   }

    public void setResolveValues(boolean resolve) {
        assignValue(ActionProvider.COMMAND_BUILD, resolve);
        assignValue(ActionProvider.COMMAND_CLEAN, resolve);
        assignValue(ActionProvider.COMMAND_REBUILD, resolve);
        assignValue("javadoc", resolve); //NOI18N
        assignValue(ActionProvider.COMMAND_TEST, resolve);
        assignValue(ActionProvider.COMMAND_TEST_SINGLE, resolve);
        assignValue(ActionProvider.COMMAND_DEBUG_TEST_SINGLE, resolve);
        assignValue(ActionProvider.COMMAND_RUN, resolve);
        assignValue(ActionProvider.COMMAND_RUN_SINGLE, resolve);
        assignValue(ActionProvider.COMMAND_DEBUG, resolve);
        assignValue(ActionProvider.COMMAND_DEBUG_SINGLE, resolve);
        assignValue(ActionProviderImpl.COMMAND_MULTIPROJECTBUILD, resolve);
        assignValue(ActionProviderImpl.COMMAND_MULTIPROJECTCLEAN, resolve);
        setEnableBrowseFields(!resolve);
   }
   
   
   private void assignValue(String actionName, boolean resolve) {
       String key = "maven.netbeans.exec." + actionName; //NOI18N
       TextFieldPropertyChange change = (TextFieldPropertyChange)changes.get(key);
       if (resolve) {
           String value = project.getPropertyResolver().resolveString(change.getNewValue());
           change.setResolvedValue(value);
       } else {
           change.resetToNonResolvedValue();
       }
   }
   
    public List getChanges() {
        List toReturn = new ArrayList();
        Iterator it = changes.values().iterator();
        while (it.hasNext()) {
            MavenPropertyChange change = (MavenPropertyChange)it.next();
            if (change.hasChanged()) {
                toReturn.add(change);
            }
        }
        return toReturn;
    }
    
    public boolean isInValidState() {
        return true;
    }
    
    public void setValidateObserver(ProjectValidateObserver observer) {
        valObserver = observer;
    }
    
    public String getValidityMessage() {
        return "";
    }
    
    private class GoalsListener implements ActionListener {
        private JTextField fld;
        public GoalsListener(JTextField field) {
            fld = field;
        }
        public void actionPerformed(java.awt.event.ActionEvent actionEvent) {
            GoalsGrabberProvider goalProvider = GoalUtils.createProjectGoalsProvider(project.getContext(), project.getLocFinder());
            CustomGoalsPanel panel = new CustomGoalsPanel(goalProvider);
            panel.setGoalsToExecute(fld.getText());
            DialogDescriptor desc = new DialogDescriptor(panel, "Select goal(s)");
            Object[] options = new Object[] {
                NotifyDescriptor.OK_OPTION,
                NotifyDescriptor.CANCEL_OPTION
            };
            desc.setOptions(options);
            desc.setClosingOptions(options);
            desc.setValue(options[0]);
            Object retValue = DialogDisplayer.getDefault().notify(desc);
            if (retValue == NotifyDescriptor.OK_OPTION) {
                fld.setText(panel.getGoalsToExecute());
            }
        }
        
    }

}
